version: '3.8'

services:
  ppe_inference_engine:
    build: .
    container_name: ppe_fastapi_core
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./model_cache:/app/model_cache
      - ./violation_crops:/app/violation_crops
      - ./temp_uploads:/app/temp_uploads
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]